-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. PROFILES Table
create table if not exists public.profiles (
  id uuid references auth.users not null primary key,
  member_id text unique,
  full_name text,
  phone text,
  address text,
  role text default 'member' check (role in ('admin', 'member')),
  status text default 'active' check (status in ('active', 'inactive')),
  join_date date default current_date,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.profiles enable row level security;

-- Policies for Profiles
drop policy if exists "Public profiles are viewable by everyone." on profiles;
create policy "Public profiles are viewable by everyone." 
  on profiles for select using ( true );

drop policy if exists "Users can insert their own profile." on profiles;
create policy "Users can insert their own profile." 
  on profiles for insert with check ( auth.uid() = id );

drop policy if exists "Users can update own profile." on profiles;
create policy "Users can update own profile." 
  on profiles for update using ( auth.uid() = id );


-- 2. LOANS Table
create table if not exists public.loans (
  id bigint generated by default as identity primary key,
  member_id uuid references public.profiles(id) not null,
  amount numeric not null check (amount > 0),
  term integer not null check (term > 0), -- in months
  interest_rate numeric not null default 1.5,
  status text default 'pending' check (status in ('pending', 'approved', 'rejected', 'paid')),
  start_date date,
  monthly_payment numeric,
  total_payment numeric,
  remaining_amount numeric,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.loans enable row level security;

-- Policies for Loans
drop policy if exists "Admin can view all loans." on loans;
create policy "Admin can view all loans." 
  on loans for select using ( 
    exists (select 1 from profiles where id = auth.uid() and role = 'admin')
  );

drop policy if exists "Members can view own loans." on loans;
create policy "Members can view own loans." 
  on loans for select using ( auth.uid() = member_id );
  
create policy "Admin can insert/update loans." 
  on loans for all using ( 
    exists (select 1 from profiles where id = auth.uid() and role = 'admin')
  );

drop policy if exists "Members can request loans." on loans;
create policy "Members can request loans." 
  on loans for insert with check ( auth.uid() = member_id );


-- 3. TRANSACTIONS Table
create table if not exists public.transactions (
  id uuid default uuid_generate_v4() primary key,
  member_id uuid references public.profiles(id) not null,
  type text not null check (type in ('simpanan', 'pinjaman', 'penarikan', 'pembayaran')),
  amount numeric not null, -- Positive for money in, Negative for money out
  description text,
  status text default 'berhasil',
  reference_id bigint references public.loans(id), -- Optional link to loan
  date timestamp with time zone default timezone('utc'::text, now()) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.transactions enable row level security;

-- Policies for Transactions
drop policy if exists "Admin can view all transactions." on transactions;
create policy "Admin can view all transactions." 
  on transactions for select using ( 
    exists (select 1 from profiles where id = auth.uid() and role = 'admin')
  );

drop policy if exists "Members can view own transactions." on transactions;
create policy "Members can view own transactions." 
  on transactions for select using ( auth.uid() = member_id );

-- 4. SAVINGS ACCOUNTS Table
create table if not exists public.savings_accounts (
  id uuid default uuid_generate_v4() primary key,
  member_id uuid references public.profiles(id) not null,
  type text not null check (type in ('simpanan_pokok', 'simpanan_wajib', 'simpanan_sukarela')),
  balance numeric not null default 0 check (balance >= 0),
  last_updated timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (member_id, type)
);

-- Enable RLS
alter table public.savings_accounts enable row level security;

-- Policies
drop policy if exists "Admin can view all savings." on savings_accounts;
create policy "Admin can view all savings." 
  on savings_accounts for select using ( 
    exists (select 1 from profiles where id = auth.uid() and role = 'admin')
  );

drop policy if exists "Members can view own savings." on savings_accounts;
create policy "Members can view own savings." 
  on savings_accounts for select using ( auth.uid() = member_id );


-- 5. LOAN REPAYMENT SCHEDULES Table
create table if not exists public.loan_schedules (
  id bigint generated by default as identity primary key,
  loan_id bigint references public.loans(id) on delete cascade not null,
  due_date date not null,
  installment_amount numeric not null,
  status text default 'unpaid' check (status in ('unpaid', 'paid', 'overdue')),
  paid_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.loan_schedules enable row level security;

-- Policies
drop policy if exists "Admin can view all schedules." on loan_schedules;
create policy "Admin can view all schedules." 
  on loan_schedules for select using ( 
    exists (select 1 from profiles where id = auth.uid() and role = 'admin')
  );

drop policy if exists "Members can view own loan schedules." on loan_schedules;
create policy "Members can view own loan schedules." 
  on loan_schedules for select using ( 
    exists (select 1 from loans where id = loan_schedules.loan_id and member_id = auth.uid())
  );


-- 6. APP CONSTANTS / CONFIG Table
create table if not exists public.app_config (
  key text primary key,
  value text not null,
  description text
);

-- Enable RLS
alter table public.app_config enable row level security;

-- Policies
drop policy if exists "Everyone can view config." on app_config;
create policy "Everyone can view config." 
  on app_config for select using ( true );

drop policy if exists "Only Admin can update config." on app_config;
create policy "Only Admin can update config." 
  on app_config for update using ( 
    exists (select 1 from profiles where id = auth.uid() and role = 'admin')
  );

-- Seed Initial Config (Only if not exists)
insert into public.app_config (key, value, description) 
values ('interest_rate_default', '1.5', 'Default flat interest rate per month in percent')
on conflict (key) do nothing;

insert into public.app_config (key, value, description) 
values ('mandatory_savings_amount', '50000', 'Monthly mandatory savings amount')
on conflict (key) do nothing;


-- 7. TRIGGER for Auto-Profile Creation
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, full_name, phone, address, role, member_id)
  values (
    new.id, 
    new.raw_user_meta_data->>'full_name', 
    new.raw_user_meta_data->>'phone', 
    new.raw_user_meta_data->>'address', 
    'member',
    'KSP-' || to_char(now(), 'YYYY') || '-' || lpad(cast(floor(random() * 10000) as text), 4, '0') -- Generate simple Member ID
  );
  return new;
end;
$$ language plpgsql security definer;

-- Drop trigger if exists to avoid duplication error (Postgres doesn't support create trigger if not exists directly)
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
